// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ttie7374@gmail.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Todo
 * @export
 * @interface PublicTodo
 */
export interface PublicTodo {
  /**
   *
   * @type {number}
   * @memberof PublicTodo
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof PublicTodo
   */
  name: string
}
