openapi: 3.0.0
info:
  version: 1.0.0
  title: swagger
  contact:
    name: swagger
    email: ttie7374@gmail.co.jp

servers:
  - url: http://localhost:8081/

tags:
  - name: public
    description: 公開

paths:
  $ref: './paths/index.yml'

components:
  $ref: './components/index.yml'
 